### ISSUE TITLE
sdk似乎没有内置接口速率限制

### ISSUE THREAD

**Issue by Albert-Gao-1** [51tracking/51tracking-sdk-java#1]
接口有默认速率限制，sdk里没有看到相关代码，使用者调用的时候要自己实现吗？

**Comment by 51tracking** [comment]
有的哦，在这部分呢，当前我们没有内置速率限制， 需要使用者自己做限制哦 
------------------------------------------------------------------
发件人：Albert-Gao-1 ***@***.***>
发送时间：2024年3月18日(星期一) 10:14
收件人：51tracking/51tracking-sdk-java ***@***.***>
抄　送：Subscribed ***@***.***>
主　题：[51tracking/51tracking-sdk-java] sdk似乎没有内置接口速率限制 (Issue #1)
接口有默认速率限制，sdk里没有看到相关代码，使用者调用的时候要自己实现吗？
